model_name_or_path: model/qwen3.5-4b
adapter_name_or_path: model/lora/schema_sft_patch_v1_api_qc_from_soda_lora_qwen35_4b_lr8e6_epoch1
trust_remote_code: true

stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

dataset_dir: data/processed/llama_factory/conclusion_chosen_sft_v1_api_qc_v1
dataset: conclusion_chosen_sft_v1_api_qc_v1_train
eval_dataset: conclusion_chosen_sft_v1_api_qc_v1_val
template: qwen3_nothink
cutoff_len: 4096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 8
dataloader_num_workers: 2

output_dir: model/lora/conclusion_chosen_sft_v1_api_qc_from_schema_sft_qwen35_4b_lr2e6_epoch2_cutoff4096
run_name: conclusion_chosen_sft_v1_api_qc_from_schema_sft_qwen35_4b_lr2e6_epoch2_cutoff4096
logging_steps: 2
save_strategy: steps
save_steps: 25
save_total_limit: 3
plot_loss: true
overwrite_output_dir: false
report_to: none

per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
max_grad_norm: 1.0
bf16: false
fp16: true
gradient_checkpointing: true
ddp_timeout: 180000000

per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 25
predict_with_generate: false
do_sample: false
packing: false
