#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import Counter
from datetime import datetime
import json
from pathlib import Path
import re
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
ALLOWED_ACTIONS = {"answer_directly", "retrieve_more", "clarify_user", "abstain"}
SAFE_ERROR_VALUES = {"", "none", "<missing>", "null", "None"}
ABSTAIN_MARKERS = (
    "现有检索证据不足",
    "现有证据不足",
    "不足以确认",
    "无法确认",
    "无法判断",
    "不能确认",
    "没有足够",
    "未能找到",
    "无法回答",
    "当前证据只能确认",
)
EXAMPLE_LIMIT = 8
TEXT_PREVIEW_CHARS = 900


DEFAULT_EXPERIMENTS = [
    {
        "name": "eval50_clean",
        "raw_dirs": [
            "data/processed/llama_factory/soda_eval50_len1800_blackbox_v2_scoped_sweep_soda_lora_gpu3_merged",
        ],
        "verifier_dir": "data/processed/llama_factory/soda_eval50_len1800_api_verifier_v2_scoped_sweep_soda_lora_gpu3_clean_v1",
    },
    {
        "name": "eval50_plus_extra300_qc_v2",
        "raw_dirs": [
            "data/processed/llama_factory/soda_eval50_len1800_blackbox_v2_scoped_sweep_soda_lora_gpu3_merged",
            "data/processed/llama_factory/soda_eval50_len1800_blackbox_extra300_v1_soda_lora_merged",
        ],
        "verifier_dir": "data/processed/llama_factory/soda_mix_eval50_clean_extra300_v1_qc_v2",
    },
]

DEFAULT_MODEL_EVALS = [
    {
        "name": "raw_soda_550_hard10_historical_overlap",
        "path": "outputs/retrieval_eval/soda_blackbox_hard10_20260530.jsonl",
        "note": "Historical Raw SODA hard10 run; same hard10 questions as verifier_soda_v2 but not same runtime settings.",
    },
    {
        "name": "raw_soda_550_strict_ablation",
        "path": "outputs/eval50_hard10_raw_soda_550_verifier_ablation",
        "note": "Strict raw-SODA baseline slot; generated by scripts/run_soda_verifier_model_ablation.sh.",
    },
    {
        "name": "verifier_soda_v2_strict_ablation",
        "path": "outputs/eval50_hard10_verifier_soda_v2_ablation",
        "note": "Strict verifier-aware SODA slot; generated by scripts/run_soda_verifier_model_ablation.sh.",
    },
    {
        "name": "raw_soda_550_cpu_gguf_ablation",
        "path": "outputs/soda_verifier_cpu_gguf_ablation/raw_soda_550_cpu_gguf",
        "note": "CPU/GGUF fallback Raw SODA slot; generated by scripts/run_soda_verifier_cpu_gguf_ablation.sh.",
    },
    {
        "name": "verifier_soda_v2_cpu_gguf_ablation",
        "path": "outputs/soda_verifier_cpu_gguf_ablation/verifier_soda_v2_cpu_gguf",
        "note": "CPU/GGUF fallback verifier-aware SODA slot; generated by scripts/run_soda_verifier_cpu_gguf_ablation.sh.",
    },
    {
        "name": "sft_api_qc_baseline",
        "path": "outputs/eval_api_qc_sft_4b_cutoff3072_mem52_20260603_134858",
        "note": "SFT/API-QC baseline; not SODA-specific.",
    },
    {
        "name": "verifier_soda_v2",
        "path": "outputs/eval_soda_api_verifier_v2",
        "note": "Verifier-aware SODA v2 LoRA; summary computed from answer jsonl.",
    },
    {
        "name": "teacher_scored_verifier_mix",
        "path": "outputs/eval_teacher_scored_kto_mix_v1_20260602_105604",
        "note": "Verifier-aware mix further filtered by teacher pair scoring.",
    },
    {
        "name": "quote80_verifier_kto",
        "path": "outputs/eval50_hard10_kto_quote80_verifier_cut5632_filtered_20260605_184448",
        "note": "Quote/action verifier KTO variant.",
    },
    {
        "name": "current_mergedbase",
        "path": "outputs/eval50_hard10_mergedbase_cutoff6656_trainenv_20260607_175322",
        "note": "Current merged-base release candidate.",
    },
]

DEFAULT_TEACHER_SCORE_EVALS = [
    {
        "name": "strict_raw_vs_verifier_teacher_score",
        "path": "outputs/runtime_teacher_scores/soda_verifier_model_ablation",
        "note": "Optional evidence-only scorer for strict Raw SODA vs Verifier-aware SODA runtime outputs.",
    },
]

DEFAULT_PAIRED_MODEL_PROBES = [
    {
        "name": "hard10_raw_soda_vs_verifier_soda_historical_overlap",
        "raw_label": "raw_soda_550",
        "raw_path": "outputs/retrieval_eval/soda_blackbox_hard10_20260530.jsonl",
        "verifier_label": "verifier_soda_v2",
        "verifier_path": "outputs/eval_soda_api_verifier_v2/hard10_answers.jsonl",
        "note": "Same hard10 questions in the same order; runtime settings differ, so this is behavioral probe evidence, not the strict ablation.",
    },
    {
        "name": "hard10_cpu_gguf_raw_soda_vs_verifier_soda",
        "raw_label": "raw_soda_550_cpu_gguf",
        "raw_path": "outputs/soda_verifier_cpu_gguf_ablation/raw_soda_550_cpu_gguf/hard10_answers.jsonl",
        "verifier_label": "verifier_soda_v2_cpu_gguf",
        "verifier_path": "outputs/soda_verifier_cpu_gguf_ablation/verifier_soda_v2_cpu_gguf/hard10_answers.jsonl",
        "note": "CPU/GGUF fallback strict-runtime hard10 slot; generated when both CPU arms complete.",
    }
]


def project_path(path: str | Path) -> Path:
    value = Path(path)
    return value if value.is_absolute() else PROJECT_ROOT / value


def read_json(path: Path) -> Any:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def parse_jsonish(value: Any) -> dict[str, Any] | None:
    if isinstance(value, dict):
        return value
    raw = str(value or "").strip()
    if not raw:
        return None
    try:
        payload = json.loads(raw)
        return payload if isinstance(payload, dict) else None
    except json.JSONDecodeError:
        pass
    start = raw.find("{")
    end = raw.rfind("}")
    if start >= 0 and end > start:
        try:
            payload = json.loads(raw[start : end + 1])
            return payload if isinstance(payload, dict) else None
        except json.JSONDecodeError:
            return None
    return None


def action_of(payload: dict[str, Any] | None) -> str:
    return str((payload or {}).get("next_action") or "").strip()


def error_value(verdict: dict[str, Any], key: str) -> str:
    return str(verdict.get(key) or "none").strip()


def is_error(value: str) -> bool:
    return value not in SAFE_ERROR_VALUES


def extract_evidence_brief(prompt: str) -> str:
    match = re.search(
        r"(?s)^evidence_brief:\s*(.*?)(?:\nminirag_hints:|\noutput_schema:|\nfields:|\Z)",
        prompt or "",
        flags=re.MULTILINE,
    )
    return match.group(1).strip() if match else ""


def normalized_text(text: str) -> str:
    return re.sub(r"\s+", "", text or "")


def truncate_text(text: Any, limit: int = TEXT_PREVIEW_CHARS) -> str:
    value = re.sub(r"\s+", " ", str(text or "")).strip()
    if len(value) <= limit:
        return value
    return value[: limit - 1].rstrip() + "..."


def collect_quotes(payload: dict[str, Any] | None) -> list[str]:
    if not isinstance(payload, dict):
        return []
    quotes: list[str] = []

    def add_quote(value: Any) -> None:
        quote = re.sub(r"\s+", " ", str(value or "")).strip()
        if quote:
            quotes.append(quote)

    for key in ("evidence_refs", "refs", "citations"):
        refs = payload.get(key)
        if isinstance(refs, list):
            for item in refs:
                if isinstance(item, dict):
                    add_quote(item.get("quote"))
    facts = payload.get("supported_facts")
    if isinstance(facts, list):
        for fact in facts:
            if not isinstance(fact, dict):
                continue
            refs = fact.get("evidence_refs")
            if isinstance(refs, list):
                for item in refs:
                    if isinstance(item, dict):
                        add_quote(item.get("quote"))
    return quotes


def compact_case(
    record: dict[str, Any],
    pair: dict[str, Any],
    teacher_payload: dict[str, Any] | None,
    student_payload: dict[str, Any] | None,
    verdict: dict[str, Any],
) -> dict[str, Any]:
    return {
        "prompt_key": record.get("prompt_key"),
        "question": record.get("question"),
        "round": record.get("round"),
        "correct_action": verdict.get("correct_action"),
        "student_action": action_of(student_payload),
        "teacher_action": action_of(teacher_payload),
        "student_error": error_value(verdict, "student_action_error"),
        "teacher_error": error_value(verdict, "teacher_action_error"),
        "teacher_prior": bool(verdict.get("teacher_answer_uses_prior_knowledge")),
        "evidence_sufficient": verdict.get("evidence_sufficient"),
        "supported_answer": truncate_text(verdict.get("supported_answer"), 500),
        "label_reason": truncate_text(verdict.get("label_reason"), 500),
        "evidence_brief_preview": truncate_text(extract_evidence_brief(str(pair.get("user_prompt") or ""))),
        "student_output_preview": truncate_text(pair.get("student_output")),
        "teacher_output_preview": truncate_text(pair.get("teacher_output")),
    }


def heuristic_accepts_teacher(pair: dict[str, Any], teacher_payload: dict[str, Any] | None) -> tuple[bool, str]:
    if not pair.get("teacher_valid", True):
        return False, "invalid_json"
    teacher_action = action_of(teacher_payload)
    if teacher_action not in ALLOWED_ACTIONS:
        return False, "invalid_action"
    quotes = collect_quotes(teacher_payload)
    if quotes:
        evidence = normalized_text(extract_evidence_brief(str(pair.get("user_prompt") or "")))
        missing = [quote for quote in quotes if normalized_text(quote) not in evidence]
        if missing:
            return False, "quote_not_in_evidence"
    return True, "accepted"


def load_raw_pairs(raw_dirs: list[Path]) -> dict[str, dict[str, Any]]:
    pairs: dict[str, dict[str, Any]] = {}
    for raw_dir in raw_dirs:
        for pair in read_jsonl(raw_dir / "raw_pairs.jsonl"):
            prompt_key = str(pair.get("prompt_key") or "")
            if prompt_key and prompt_key not in pairs:
                pairs[prompt_key] = pair
    return pairs


def load_verifier_records(verifier_dir: Path) -> list[dict[str, Any]]:
    rows = []
    for record in read_jsonl(verifier_dir / "api_verifier_records.jsonl"):
        verdict = record.get("verifier")
        if record.get("error") or not isinstance(verdict, dict):
            continue
        correct_action = str(verdict.get("correct_action") or "").strip()
        if correct_action in ALLOWED_ACTIONS:
            rows.append(record)
    return rows


def count_dataset_relabels(verifier_dir: Path) -> dict[str, Any]:
    records = []
    for filename in ("train.json", "val.json"):
        payload = read_json(verifier_dir / filename)
        if isinstance(payload, list):
            records.extend(payload)
    stats: Counter[str] = Counter()
    chosen_action_mismatch = 0
    chosen_total = 0
    for record in records:
        if record.get("task_type") != "conclusion_generation":
            continue
        meta = record.get("meta") if isinstance(record.get("meta"), dict) else {}
        reason = str(meta.get("api_verifier_reason") or "")
        if reason:
            stats[f"reason:{reason}"] += 1
        if bool(record.get("kto_tag")) and reason.startswith("verifier_chosen_"):
            chosen_total += 1
            payload = None
            conversations = record.get("conversations")
            if isinstance(conversations, list) and conversations:
                payload = parse_jsonish(conversations[-1].get("value"))
            if action_of(payload) != str(meta.get("verifier_correct_action") or ""):
                chosen_action_mismatch += 1
    return {
        "conclusion_verifier_chosen": chosen_total,
        "conclusion_chosen_action_mismatch": chosen_action_mismatch,
        "reason_counts": dict(sorted(stats.items())),
    }


def analyze_quality_experiment(name: str, raw_dirs: list[Path], verifier_dir: Path) -> dict[str, Any]:
    pairs = load_raw_pairs(raw_dirs)
    verifier_records = load_verifier_records(verifier_dir)
    stats: Counter[str] = Counter()
    teacher_errors: Counter[str] = Counter()
    student_errors: Counter[str] = Counter()
    heuristic_drop_reasons: Counter[str] = Counter()
    examples: dict[str, list[dict[str, Any]]] = {
        "raw_teacher_unsafe": [],
        "student_better_than_teacher": [],
        "heuristic_false_accept": [],
    }

    for record in verifier_records:
        prompt_key = str(record.get("prompt_key") or "")
        verdict = record.get("verifier") if isinstance(record.get("verifier"), dict) else {}
        pair = pairs.get(prompt_key)
        if pair is None:
            stats["missing_raw_pair"] += 1
            continue
        stats["prompts"] += 1
        correct_action = str(verdict.get("correct_action") or "").strip()
        teacher_payload = parse_jsonish(pair.get("teacher_output"))
        student_payload = parse_jsonish(pair.get("student_output"))
        teacher_action = action_of(teacher_payload)
        student_action = action_of(student_payload)
        teacher_error = error_value(verdict, "teacher_action_error")
        student_error = error_value(verdict, "student_action_error")
        teacher_prior = bool(verdict.get("teacher_answer_uses_prior_knowledge"))
        teacher_errors[teacher_error] += 1
        student_errors[student_error] += 1

        teacher_unsafe = (
            not pair.get("teacher_valid", True)
            or teacher_action not in ALLOWED_ACTIONS
            or teacher_action != correct_action
            or is_error(teacher_error)
            or teacher_prior
        )
        student_unsafe = (
            not pair.get("student_valid", True)
            or student_action not in ALLOWED_ACTIONS
            or student_action != correct_action
            or is_error(student_error)
        )
        if teacher_action != correct_action:
            stats["raw_teacher_action_mismatch"] += 1
        if student_action != correct_action:
            stats["student_action_mismatch"] += 1
        if teacher_unsafe:
            stats["raw_teacher_unsafe_chosen"] += 1
            if len(examples["raw_teacher_unsafe"]) < EXAMPLE_LIMIT:
                examples["raw_teacher_unsafe"].append(
                    compact_case(record, pair, teacher_payload, student_payload, verdict)
                )
        if not student_unsafe and teacher_unsafe:
            stats["student_better_than_teacher"] += 1
            if len(examples["student_better_than_teacher"]) < EXAMPLE_LIMIT:
                examples["student_better_than_teacher"].append(
                    compact_case(record, pair, teacher_payload, student_payload, verdict)
                )
        if teacher_prior:
            stats["raw_teacher_prior_leak"] += 1
        if teacher_error in {"unsupported_answer", "teacher_prior_knowledge"} or teacher_prior:
            stats["raw_teacher_unsupported_or_prior"] += 1
        if teacher_error == "premature_answer":
            stats["raw_teacher_premature_answer"] += 1
        if teacher_error == "over_retrieve":
            stats["raw_teacher_over_retrieve"] += 1
        if student_error == "premature_answer":
            stats["student_premature_answer"] += 1
        if student_error == "unsupported_answer":
            stats["student_unsupported_answer"] += 1
        if student_error == "over_retrieve":
            stats["student_over_retrieve"] += 1

        accepted, drop_reason = heuristic_accepts_teacher(pair, teacher_payload)
        heuristic_drop_reasons[drop_reason] += 1
        if accepted:
            stats["heuristic_teacher_accepted"] += 1
            if teacher_unsafe:
                stats["heuristic_unsafe_accepted"] += 1
                if len(examples["heuristic_false_accept"]) < EXAMPLE_LIMIT:
                    examples["heuristic_false_accept"].append(
                        compact_case(record, pair, teacher_payload, student_payload, verdict)
                    )
            if teacher_error in {"unsupported_answer", "teacher_prior_knowledge"} or teacher_prior:
                stats["heuristic_unsupported_or_prior_accepted"] += 1
        elif teacher_unsafe:
            stats["heuristic_unsafe_dropped"] += 1

    relabels = count_dataset_relabels(verifier_dir)
    return {
        "name": name,
        "raw_dirs": [str(path.relative_to(PROJECT_ROOT)) if path.is_relative_to(PROJECT_ROOT) else str(path) for path in raw_dirs],
        "verifier_dir": str(verifier_dir.relative_to(PROJECT_ROOT)) if verifier_dir.is_relative_to(PROJECT_ROOT) else str(verifier_dir),
        "stats": dict(stats),
        "teacher_error_counts": dict(sorted(teacher_errors.items())),
        "student_error_counts": dict(sorted(student_errors.items())),
        "heuristic_drop_reasons": dict(sorted(heuristic_drop_reasons.items())),
        "relabels": relabels,
        "examples": examples,
    }


def rate(numerator: int | float, denominator: int | float) -> float | None:
    if not denominator:
        return None
    return round(float(numerator) / float(denominator), 4)


def raw_rate(numerator: int | float, denominator: int | float) -> float | None:
    if not denominator:
        return None
    return float(numerator) / float(denominator)


def count_rate(count: int, denominator: int) -> str:
    return f"{count} ({md_rate(rate(count, denominator))})"


def relative_reduction(before: int, after: int) -> str:
    if before <= 0:
        return "n/a"
    return md_rate(rate(before - after, before))


def percentage_point_delta(before: int, after: int, denominator: int) -> str:
    before_rate = raw_rate(before, denominator) or 0.0
    after_rate = raw_rate(after, denominator) or 0.0
    return f"{(before_rate - after_rate) * 100:.2f} pp"


def final_action(row: dict[str, Any]) -> str:
    trace = row.get("retrieval_trace")
    if isinstance(trace, list) and trace:
        last = trace[-1] if isinstance(trace[-1], dict) else {}
        return str(last.get("planner_action") or "")
    return str(row.get("final_action") or "")


def summarize_rows(rows: list[dict[str, Any]], name: str) -> dict[str, Any]:
    counter: Counter[str] = Counter()
    action_sequences: Counter[str] = Counter()
    elapsed = []
    marker_re = re.compile("|".join(re.escape(item) for item in ABSTAIN_MARKERS))
    for row in rows:
        counter["count"] += 1
        if row.get("error"):
            counter["errors"] += 1
        if marker_re.search(str(row.get("answer") or "")) or final_action(row) == "abstain":
            counter["abstain_like"] += 1
        action = final_action(row)
        counter[f"final_action:{action}"] += 1
        trace = row.get("retrieval_trace")
        if isinstance(trace, list) and trace:
            seq = ">".join(str((item or {}).get("planner_action") or "") for item in trace if isinstance(item, dict))
        else:
            seq = action
        action_sequences[seq] += 1
        try:
            elapsed.append(float(row.get("elapsed_sec")))
        except (TypeError, ValueError):
            pass
    return {
        "name": name,
        "count": counter["count"],
        "errors": counter["errors"],
        "abstain_like": counter["abstain_like"],
        "final_actions": {
            key.split(":", 1)[1]: value
            for key, value in sorted(counter.items())
            if key.startswith("final_action:")
        },
        "action_sequences": dict(sorted(action_sequences.items())),
        "avg_elapsed_sec": round(sum(elapsed) / len(elapsed), 3) if elapsed else None,
    }


def summarize_eval_path(path: Path) -> dict[str, Any]:
    if path.is_file():
        rows = read_jsonl(path)
        dataset_name = "hard10" if "hard10" in path.name else "eval50" if "eval50" in path.name else path.stem
        return {"source": path.name, "summaries": [summarize_rows(rows, dataset_name)] if rows else []}
    summaries = []
    for name in ("eval50", "hard10"):
        rows = read_jsonl(path / f"{name}_answers.jsonl")
        if rows:
            summaries.append(summarize_rows(rows, name))
    if summaries:
        return {"source": "answers.jsonl", "summaries": summaries}
    summary = read_json(path / "summary.json")
    if isinstance(summary, dict) and isinstance(summary.get("summaries"), list):
        return {"source": "summary.json", "summaries": summary["summaries"]}
    return {"source": "answers.jsonl", "summaries": summaries}


def runtime_summary_status(summary: dict[str, Any], *, expected_count: int | None = None) -> str:
    count = int(summary.get("count") or 0)
    errors = int(summary.get("errors") or 0)
    final_actions = summary.get("final_actions") if isinstance(summary.get("final_actions"), dict) else {}
    non_empty_actions = sum(int(value) for key, value in final_actions.items() if str(key).strip())
    if count <= 0:
        return "invalid: empty output"
    if expected_count is not None and count < expected_count:
        return f"incomplete: {count}/{expected_count}"
    if errors >= count:
        return "invalid: all rows failed"
    if errors:
        return f"partial: {errors}/{count} rows failed"
    if non_empty_actions == 0:
        return "invalid: no parsed final action"
    return "valid behavioral evidence"


def collect_model_effects(model_evals: list[dict[str, str]]) -> list[dict[str, Any]]:
    output = []
    for item in model_evals:
        path = project_path(item["path"])
        if not path.exists():
            output.append({"name": item["name"], "path": item["path"], "missing": True, "note": item.get("note", "")})
            continue
        payload = summarize_eval_path(path)
        payload.update({"name": item["name"], "path": item["path"], "missing": False, "note": item.get("note", "")})
        output.append(payload)
    return output


def final_runtime(row: dict[str, Any]) -> dict[str, Any]:
    runtime = row.get("model_runtime")
    return runtime if isinstance(runtime, dict) else {}


def runtime_signature(row: dict[str, Any]) -> dict[str, Any]:
    runtime = final_runtime(row)
    strategy = runtime.get("prompt_evidence_strategy")
    strategy = strategy if isinstance(strategy, dict) else {}
    return {
        "lora_path": runtime.get("lora_path"),
        "generator_backend": runtime.get("generator_backend"),
        "max_model_len": runtime.get("max_model_len"),
        "gpu_memory_utilization": runtime.get("gpu_memory_utilization"),
        "max_num_batched_tokens": runtime.get("max_num_batched_tokens"),
        "enforce_eager": runtime.get("enforce_eager"),
        "web_context_enabled": strategy.get("web_context_enabled"),
        "prompt_top_k": strategy.get("top_k"),
    }


def load_eval_rows(path: Path) -> list[dict[str, Any]]:
    if path.is_file():
        return read_jsonl(path)
    for filename in ("hard10_answers.jsonl", "eval50_answers.jsonl", "answers.jsonl"):
        rows = read_jsonl(path / filename)
        if rows:
            return rows
    return []


def summarize_paired_model_probe(item: dict[str, str]) -> dict[str, Any]:
    raw_path = project_path(item["raw_path"])
    verifier_path = project_path(item["verifier_path"])
    raw_rows = load_eval_rows(raw_path)
    verifier_rows = load_eval_rows(verifier_path)
    raw_by_q = {str(row.get("question") or ""): row for row in raw_rows}
    verifier_by_q = {str(row.get("question") or ""): row for row in verifier_rows}
    questions = [question for question in raw_by_q if question and question in verifier_by_q]
    stats: Counter[str] = Counter()
    action_pairs: Counter[str] = Counter()
    examples = []
    marker_re = re.compile("|".join(re.escape(item) for item in ABSTAIN_MARKERS))

    for question in questions:
        raw = raw_by_q[question]
        verifier = verifier_by_q[question]
        raw_action = final_action(raw)
        verifier_action = final_action(verifier)
        action_pairs[f"{raw_action or '<empty>'}->{verifier_action or '<empty>'}"] += 1
        if raw.get("error"):
            stats["raw_errors"] += 1
        if verifier.get("error"):
            stats["verifier_errors"] += 1
        raw_abstain_like = raw_action == "abstain" or bool(marker_re.search(str(raw.get("answer") or "")))
        verifier_abstain_like = verifier_action == "abstain" or bool(marker_re.search(str(verifier.get("answer") or "")))
        if raw_abstain_like:
            stats["raw_abstain_like"] += 1
        if verifier_abstain_like:
            stats["verifier_abstain_like"] += 1
        stats[f"raw_action:{raw_action}"] += 1
        stats[f"verifier_action:{verifier_action}"] += 1
        if raw_action != verifier_action:
            stats["action_changed"] += 1
            if len(examples) < EXAMPLE_LIMIT:
                examples.append(
                    {
                        "question": question,
                        "raw_action": raw_action,
                        "verifier_action": verifier_action,
                        "raw_answer": truncate_text(raw.get("answer"), 360),
                        "verifier_answer": truncate_text(verifier.get("answer"), 360),
                    }
                )

    status = "valid behavioral probe"
    if not questions:
        status = "invalid: no overlapping questions"
    elif stats["raw_errors"] or stats["verifier_errors"]:
        status = f"invalid: runtime errors raw={stats['raw_errors']} verifier={stats['verifier_errors']}"
    elif action_pairs and set(action_pairs) == {"<empty>-><empty>"}:
        status = "invalid: no parsed final actions"

    return {
        "name": item["name"],
        "raw_label": item["raw_label"],
        "raw_path": item["raw_path"],
        "verifier_label": item["verifier_label"],
        "verifier_path": item["verifier_path"],
        "note": item.get("note", ""),
        "evidence_status": status,
        "paired_count": len(questions),
        "stats": dict(stats),
        "action_pairs": dict(sorted(action_pairs.items())),
        "raw_runtime": runtime_signature(raw_rows[0]) if raw_rows else {},
        "verifier_runtime": runtime_signature(verifier_rows[0]) if verifier_rows else {},
        "examples": examples,
    }


def collect_paired_model_probes(items: list[dict[str, str]]) -> list[dict[str, Any]]:
    return [summarize_paired_model_probe(item) for item in items]


def scorer_number(score: dict[str, Any], keys: tuple[str, ...]) -> float | None:
    for key in keys:
        try:
            value = score.get(key)
            if value is not None:
                return float(value)
        except (TypeError, ValueError):
            continue
    return None


def scorer_errors(score: dict[str, Any]) -> set[str]:
    output: set[str] = set()
    for key in ("serious_errors", "errors"):
        values = score.get(key)
        if isinstance(values, list):
            output.update(str(item) for item in values if str(item))
    action_error = str(score.get("action_error") or "")
    if action_error and action_error != "none":
        output.add(action_error)
    error_type = str(score.get("error_type") or "")
    if error_type and error_type != "none":
        output.add(error_type)
    if score.get("unsupported"):
        output.add("unsupported")
    if score.get("contradicted"):
        output.add("contradicted")
    return output


def summarize_teacher_score_pairs(records: list[dict[str, Any]]) -> dict[str, Any]:
    by_key: dict[tuple[str, int], dict[str, dict[str, Any]]] = {}
    for record in records:
        case = record.get("case") if isinstance(record.get("case"), dict) else {}
        run = str(case.get("run_label") or "")
        if run not in {"raw_soda", "verifier_soda"}:
            continue
        dataset = str(case.get("dataset") or "")
        try:
            index = int(case.get("index"))
        except (TypeError, ValueError):
            continue
        by_key.setdefault((dataset, index), {})[run] = record

    paired = [runs for runs in by_key.values() if {"raw_soda", "verifier_soda"} <= set(runs)]
    if not paired:
        return {"paired_count": 0}

    deltas: Counter[str] = Counter()
    numeric_acc: dict[str, list[float]] = {"action": [], "support": [], "reward": []}
    for runs in paired:
        raw_score = runs["raw_soda"].get("score") if isinstance(runs["raw_soda"].get("score"), dict) else {}
        verifier_score = (
            runs["verifier_soda"].get("score") if isinstance(runs["verifier_soda"].get("score"), dict) else {}
        )
        for key, score_keys in {
            "action": ("action_score",),
            "support": ("support_score", "evidence_support"),
            "reward": ("reward_score",),
        }.items():
            raw_value = scorer_number(raw_score, score_keys)
            verifier_value = scorer_number(verifier_score, score_keys)
            if raw_value is not None and verifier_value is not None:
                numeric_acc[key].append(verifier_value - raw_value)

        raw_label = str(raw_score.get("label") or "")
        verifier_label = str(verifier_score.get("label") or "")
        if raw_label == "negative":
            deltas["raw_negative"] += 1
        if verifier_label == "negative":
            deltas["verifier_negative"] += 1
        raw_errors = scorer_errors(raw_score)
        verifier_errors = scorer_errors(verifier_score)
        for error in ("unsupported", "premature_answer", "over_abstain", "contradicted"):
            if error in raw_errors:
                deltas[f"raw_error:{error}"] += 1
            if error in verifier_errors:
                deltas[f"verifier_error:{error}"] += 1

    def avg(values: list[float]) -> float | None:
        return round(sum(values) / len(values), 4) if values else None

    return {
        "paired_count": len(paired),
        "avg_action_delta_verifier_minus_raw": avg(numeric_acc["action"]),
        "avg_support_delta_verifier_minus_raw": avg(numeric_acc["support"]),
        "avg_reward_delta_verifier_minus_raw": avg(numeric_acc["reward"]),
        "raw_negative": deltas["raw_negative"],
        "verifier_negative": deltas["verifier_negative"],
        "raw_unsupported": deltas["raw_error:unsupported"],
        "verifier_unsupported": deltas["verifier_error:unsupported"],
        "raw_premature": deltas["raw_error:premature_answer"],
        "verifier_premature": deltas["verifier_error:premature_answer"],
        "raw_over_abstain": deltas["raw_error:over_abstain"],
        "verifier_over_abstain": deltas["verifier_error:over_abstain"],
    }


def collect_teacher_score_effects(score_evals: list[dict[str, str]]) -> list[dict[str, Any]]:
    output = []
    for item in score_evals:
        path = project_path(item["path"])
        summary = read_json(path / "summary.json")
        if not isinstance(summary, dict):
            output.append({"name": item["name"], "path": item["path"], "missing": True, "note": item.get("note", "")})
            continue
        records = read_jsonl(path / "teacher_answer_scores.jsonl")
        output.append(
            {
                "name": item["name"],
                "path": item["path"],
                "missing": False,
                "note": item.get("note", ""),
                "summary": summary,
                "paired": summarize_teacher_score_pairs(records),
            }
        )
    return output


def md_rate(value: float | None) -> str:
    return "n/a" if value is None else f"{value:.2%}"


def render_policy_delta_table(result: dict[str, Any]) -> list[str]:
    stats = Counter(result["stats"])
    prompts = stats["prompts"]
    relabels = result["relabels"]
    verifier_chosen = int(relabels["conclusion_verifier_chosen"])
    verifier_unsafe = int(relabels["conclusion_chosen_action_mismatch"])
    raw_unsafe = stats["raw_teacher_unsafe_chosen"]
    raw_unsupported_prior = stats["raw_teacher_unsupported_or_prior"]
    raw_action_mismatch = stats["raw_teacher_action_mismatch"]
    heuristic_detected_unsafe = stats["heuristic_unsafe_dropped"]
    heuristic_false_accept = stats["heuristic_unsafe_accepted"]
    lines = [
        "| Paired measurement | Raw SODA | Output-only heuristic | Verifier-aware SODA | Delta / interpretation |",
        "| --- | ---: | ---: | ---: | --- |",
        "| unsafe chosen by verifier-defined label | "
        + f"{count_rate(raw_unsafe, prompts)} | {count_rate(heuristic_false_accept, stats['heuristic_teacher_accepted'])} | "
        + f"{count_rate(verifier_unsafe, verifier_chosen)} | "
        + f"absolute reduction {raw_unsafe - verifier_unsafe}/{prompts}; relative reduction {relative_reduction(raw_unsafe, verifier_unsafe)} |",
        "| unsupported/prior-positive contamination | "
        + f"{count_rate(raw_unsupported_prior, prompts)} | {count_rate(stats['heuristic_unsupported_or_prior_accepted'], stats['heuristic_teacher_accepted'])} | "
        + f"0 ({md_rate(0.0)}) | evidence-only relabel removes teacher-prior positives by construction |",
        "| action mismatch against verifier action | "
        + f"{count_rate(raw_action_mismatch, prompts)} | n/a | {count_rate(verifier_unsafe, verifier_chosen)} | "
        + f"absolute reduction {raw_action_mismatch - verifier_unsafe}; rate delta {percentage_point_delta(raw_action_mismatch, verifier_unsafe, prompts)} |",
        "| unsafe teacher candidates detected by output-only checks | "
        + f"n/a | {count_rate(heuristic_detected_unsafe, raw_unsafe)} | n/a | negative control recall over unsafe teachers |",
        "| unsafe teacher candidates missed by output-only checks | "
        + f"n/a | {count_rate(heuristic_false_accept, raw_unsafe)} | n/a | JSON/action/quote checks cannot judge evidence sufficiency or teacher prior |",
        "| safe student while teacher unsafe | "
        + f"{count_rate(stats['student_better_than_teacher'], prompts)} | n/a | used by relabel policy | teacher identity is not a reliable positive-label proxy |",
        "",
    ]
    return lines


def render_quality_table(result: dict[str, Any]) -> list[str]:
    stats = Counter(result["stats"])
    prompts = stats["prompts"]
    heuristic_accepted = stats["heuristic_teacher_accepted"]
    relabels = result["relabels"]
    lines = [
        f"### {result['name']}",
        "",
        f"- raw_dirs: `{', '.join(result['raw_dirs'])}`",
        f"- verifier_dir: `{result['verifier_dir']}`",
        f"- conclusion prompts with verifier and raw pair: `{prompts}`",
        "",
        "| Strategy | Accepted chosen | Unsafe chosen | Unsafe rate | Unsupported/prior accepted | Action mismatch | Notes |",
        "| --- | ---: | ---: | ---: | ---: | ---: | --- |",
        "| Raw SODA teacher-as-chosen | "
        + f"{prompts} | {stats['raw_teacher_unsafe_chosen']} | {md_rate(rate(stats['raw_teacher_unsafe_chosen'], prompts))} | "
        + f"{stats['raw_teacher_unsupported_or_prior']} | {stats['raw_teacher_action_mismatch']} | teacher is always positive |",
        "| Output-only heuristic | "
        + f"{heuristic_accepted} | {stats['heuristic_unsafe_accepted']} | {md_rate(rate(stats['heuristic_unsafe_accepted'], heuristic_accepted))} | "
        + f"{stats['heuristic_unsupported_or_prior_accepted']} | n/a | only JSON/action/exact quote checks |",
        "| Verifier-aware relabel | "
        + f"{relabels['conclusion_verifier_chosen']} | {relabels['conclusion_chosen_action_mismatch']} | "
        + f"{md_rate(rate(relabels['conclusion_chosen_action_mismatch'], relabels['conclusion_verifier_chosen']))} | 0 by verifier policy | 0 by verifier policy | chosen action is rebuilt from verifier correct_action |",
        "",
    ]
    lines.extend(render_policy_delta_table(result))
    lines.extend(
        [
        "| Error source | Count | Rate over prompts |",
        "| --- | ---: | ---: |",
        f"| teacher prior knowledge risk | {stats['raw_teacher_prior_leak']} | {md_rate(rate(stats['raw_teacher_prior_leak'], prompts))} |",
        f"| teacher premature answer | {stats['raw_teacher_premature_answer']} | {md_rate(rate(stats['raw_teacher_premature_answer'], prompts))} |",
        f"| teacher over-retrieve | {stats['raw_teacher_over_retrieve']} | {md_rate(rate(stats['raw_teacher_over_retrieve'], prompts))} |",
        f"| student unsupported answer | {stats['student_unsupported_answer']} | {md_rate(rate(stats['student_unsupported_answer'], prompts))} |",
        f"| student premature answer | {stats['student_premature_answer']} | {md_rate(rate(stats['student_premature_answer'], prompts))} |",
        f"| student over-retrieve | {stats['student_over_retrieve']} | {md_rate(rate(stats['student_over_retrieve'], prompts))} |",
        f"| student safe while teacher unsafe | {stats['student_better_than_teacher']} | {md_rate(rate(stats['student_better_than_teacher'], prompts))} |",
        "",
        "Teacher error distribution:",
        "",
        ]
    )
    lines.extend(f"- `{key}`: {value}" for key, value in result["teacher_error_counts"].items())
    lines.extend(["", "Student error distribution:", ""])
    lines.extend(f"- `{key}`: {value}" for key, value in result["student_error_counts"].items())
    lines.extend(["", "Heuristic drop reasons:", ""])
    lines.extend(f"- `{key}`: {value}" for key, value in result["heuristic_drop_reasons"].items())
    lines.extend(["", "Verifier relabel reasons:", ""])
    reason_counts = result["relabels"]["reason_counts"]
    lines.extend(f"- `{key.replace('reason:', '')}`: {value}" for key, value in reason_counts.items())
    return lines


def render_model_table(model_effects: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Model Effect Evidence",
        "",
        "These rows are existing runtime evaluations. They are useful behavioral evidence, but only rows produced under the same question set and runtime should be treated as strict model-effect ablations.",
        "",
        "| Model/eval | Dataset | Count | Errors | Abstain-like | Answer directly | Abstain | Evidence status | Source | Note |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | --- | --- | --- |",
    ]
    for item in model_effects:
        if item.get("missing"):
            lines.append(
                f"| `{item['name']}` | missing | 0 | 0 | 0 | 0 | 0 | missing | `{item['path']}` | {item.get('note', '')} |"
            )
            continue
        for summary in item.get("summaries", []):
            final_actions = summary.get("final_actions") if isinstance(summary.get("final_actions"), dict) else {}
            expected_count = 10 if summary.get("name") == "hard10" else 50 if summary.get("name") == "eval50" else None
            status = runtime_summary_status(summary, expected_count=expected_count)
            lines.append(
                f"| `{item['name']}` | {summary.get('name')} | {summary.get('count', 0)} | {summary.get('errors', 0)} | "
                f"{summary.get('abstain_like', 0)} | {final_actions.get('answer_directly', 0)} | {final_actions.get('abstain', 0)} | "
                f"{status} | `{item.get('source')}` | {item.get('note', '')} |"
            )
    return lines


def render_runtime_signature(signature: dict[str, Any]) -> str:
    keys = (
        "generator_backend",
        "max_model_len",
        "gpu_memory_utilization",
        "max_num_batched_tokens",
        "enforce_eager",
        "web_context_enabled",
        "prompt_top_k",
    )
    return ", ".join(f"{key}={signature.get(key)}" for key in keys)


def render_paired_model_probe_table(probes: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Paired Historical Model Probe",
        "",
        "These rows compare existing model outputs on overlapping questions. They provide additional behavioral evidence, but they are not strict model-effect ablations unless the runtime signatures are identical.",
        "",
        "| Probe | Pairs | Raw errors | Verifier errors | Raw abstain-like | Verifier abstain-like | Raw answer_directly | Verifier answer_directly | Action changed | Evidence status | Note |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for probe in probes:
        stats = Counter(probe.get("stats") if isinstance(probe.get("stats"), dict) else {})
        paired_count = int(probe.get("paired_count") or 0)
        lines.append(
            f"| `{probe.get('name')}` | {paired_count} | {stats['raw_errors']} | {stats['verifier_errors']} | "
            f"{stats['raw_abstain_like']} | {stats['verifier_abstain_like']} | {stats['raw_action:answer_directly']} | "
            f"{stats['verifier_action:answer_directly']} | {stats['action_changed']} | {probe.get('evidence_status', 'unknown')} | {probe.get('note', '')} |"
        )
    for probe in probes:
        lines.extend(
            [
                "",
                f"Runtime signatures for `{probe.get('name')}`:",
                "",
                f"- raw: {render_runtime_signature(probe.get('raw_runtime') if isinstance(probe.get('raw_runtime'), dict) else {})}",
                f"- verifier: {render_runtime_signature(probe.get('verifier_runtime') if isinstance(probe.get('verifier_runtime'), dict) else {})}",
            ]
        )
        action_pairs = probe.get("action_pairs") if isinstance(probe.get("action_pairs"), dict) else {}
        if action_pairs:
            lines.extend(["", "Action pair distribution:", ""])
            lines.extend(f"- `{key}`: {value}" for key, value in action_pairs.items())
        examples = probe.get("examples") if isinstance(probe.get("examples"), list) else []
        if examples:
            lines.extend(["", "Action-change examples:", ""])
            for example in examples[:5]:
                lines.extend(
                    [
                        f"- {example.get('question')}",
                        f"  raw/verifier action: `{example.get('raw_action')}` / `{example.get('verifier_action')}`",
                    ]
                )
    return lines


def md_optional(value: Any) -> Any:
    return "n/a" if value is None else value


def render_teacher_score_table(score_effects: list[dict[str, Any]]) -> list[str]:
    lines = [
        "## Runtime Answer Scorer Evidence",
        "",
        "This table is populated when strict model outputs are scored by `scripts/score_runtime_answers_with_teacher.py`. It is the preferred model-effect layer because the scorer sees the runtime evidence and flags unsupported, premature, contradicted or over-abstain behavior.",
        "",
        "| Score/eval | Run | Count | Positive | Neutral | Negative | Unsupported | Premature | Over-abstain | Avg action | Avg support | Avg reward | Source | Note |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for item in score_effects:
        if item.get("missing"):
            lines.append(
                f"| `{item['name']}` | missing | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | `{item['path']}` | {item.get('note', '')} |"
            )
            continue
        summary = item.get("summary") if isinstance(item.get("summary"), dict) else {}
        runs = summary.get("runs") if isinstance(summary.get("runs"), dict) else {}
        for run, payload in sorted(runs.items()):
            if not isinstance(payload, dict):
                continue
            labels = payload.get("labels") if isinstance(payload.get("labels"), dict) else {}
            errors = payload.get("errors") if isinstance(payload.get("errors"), dict) else {}
            avg_action = payload.get("avg_action_score", payload.get("avg_reward_score", "n/a"))
            avg_support = payload.get("avg_support_score", payload.get("avg_evidence_support", "n/a"))
            avg_reward = payload.get("avg_reward_score", "n/a")
            lines.append(
                f"| `{item['name']}` | `{run}` | {payload.get('count', 0)} | {labels.get('positive', 0)} | "
                f"{labels.get('neutral', 0)} | {labels.get('negative', 0)} | {errors.get('unsupported', 0)} | "
                f"{errors.get('premature_answer', 0)} | {errors.get('over_abstain', 0)} | {avg_action} | "
                f"{avg_support} | {avg_reward} | `{item['path']}/summary.json` | {item.get('note', '')} |"
            )
        paired = item.get("paired") if isinstance(item.get("paired"), dict) else {}
        if paired.get("paired_count"):
            lines.extend(
                [
                    "",
                    "Paired scorer deltas for `verifier_soda - raw_soda`:",
                    "",
                    "| Pairs | Action score delta | Support score delta | Reward delta | Negative delta | Unsupported delta | Premature delta | Over-abstain delta |",
                    "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
                    f"| {paired.get('paired_count', 0)} | {md_optional(paired.get('avg_action_delta_verifier_minus_raw'))} | "
                    f"{md_optional(paired.get('avg_support_delta_verifier_minus_raw'))} | {md_optional(paired.get('avg_reward_delta_verifier_minus_raw'))} | "
                    f"{paired.get('verifier_negative', 0) - paired.get('raw_negative', 0)} | "
                    f"{paired.get('verifier_unsupported', 0) - paired.get('raw_unsupported', 0)} | "
                    f"{paired.get('verifier_premature', 0) - paired.get('raw_premature', 0)} | "
                    f"{paired.get('verifier_over_abstain', 0) - paired.get('raw_over_abstain', 0)} |",
                ]
            )
    return lines


def strict_summary_by_dataset(
    model_effects: list[dict[str, Any]],
    *,
    model_name: str,
    dataset_name: str,
) -> dict[str, Any] | None:
    for item in model_effects:
        if item.get("name") != model_name:
            continue
        for summary in item.get("summaries", []):
            if summary.get("name") == dataset_name:
                return summary
    return None


def strict_summary_is_complete(summary: dict[str, Any] | None, *, expected_count: int) -> bool:
    if not summary:
        return False
    return int(summary.get("count") or 0) == expected_count and int(summary.get("errors") or 0) == 0


def render_strict_model_effect_status(model_effects: list[dict[str, Any]]) -> list[str]:
    raw_eval50 = strict_summary_by_dataset(
        model_effects,
        model_name="raw_soda_550_strict_ablation",
        dataset_name="eval50",
    )
    raw_hard10 = strict_summary_by_dataset(
        model_effects,
        model_name="raw_soda_550_strict_ablation",
        dataset_name="hard10",
    )
    verifier_eval50 = strict_summary_by_dataset(
        model_effects,
        model_name="verifier_soda_v2_strict_ablation",
        dataset_name="eval50",
    )
    verifier_hard10 = strict_summary_by_dataset(
        model_effects,
        model_name="verifier_soda_v2_strict_ablation",
        dataset_name="hard10",
    )
    complete = (
        strict_summary_is_complete(raw_eval50, expected_count=50)
        and strict_summary_is_complete(verifier_eval50, expected_count=50)
        and strict_summary_is_complete(raw_hard10, expected_count=10)
        and strict_summary_is_complete(verifier_hard10, expected_count=10)
    )

    if complete:
        pairs = [
            ("eval50", raw_eval50 or {}, verifier_eval50 or {}),
            ("hard10", raw_hard10 or {}, verifier_hard10 or {}),
        ]
        lines = [
            "## Strict Model-Effect Ablation Completed",
            "",
            "Raw SODA and Verifier-aware SODA have been evaluated with the strict wrapper under the same question files, runtime config, decoding settings, GPU count and retrieval-round budget. Both arms are complete and have zero runtime errors.",
            "",
            "| Dataset | Raw count/errors | Verifier count/errors | Raw answer_directly | Verifier answer_directly | Raw abstain | Verifier abstain | Raw avg sec | Verifier avg sec |",
            "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
        for dataset, raw, verifier in pairs:
            raw_actions = raw.get("final_actions") if isinstance(raw.get("final_actions"), dict) else {}
            verifier_actions = verifier.get("final_actions") if isinstance(verifier.get("final_actions"), dict) else {}
            lines.append(
                f"| {dataset} | {raw.get('count', 0)}/{raw.get('errors', 0)} | {verifier.get('count', 0)}/{verifier.get('errors', 0)} | "
                f"{raw_actions.get('answer_directly', 0)} | {verifier_actions.get('answer_directly', 0)} | "
                f"{raw_actions.get('abstain', 0)} | {verifier_actions.get('abstain', 0)} | "
                f"{raw.get('avg_elapsed_sec', 'n/a')} | {verifier.get('avg_elapsed_sec', 'n/a')} |"
            )
        lines.extend(
            [
                "",
                "The runtime answer scorer section above provides the evidence-only quality layer for the same strict outputs. Runtime summary shows the controlled action-policy shift; scorer deltas separate supported answers from over-abstain and premature-answer errors.",
                "",
                "To refresh evidence-only answer scoring after new strict outputs:",
                "",
                "```bash",
                "RUN_TEACHER_SCORE=1 \\",
                "RUN_RAW=0 RUN_VERIFIER=0 \\",
                "PYTHON_BIN=/home/zhb/miniconda3/envs/train/bin/python \\",
                "bash scripts/run_soda_verifier_model_ablation.sh",
                "```",
            ]
        )
        return lines

    return [
        "## Strict Model-Effect Ablation Still Needed",
        "",
        "The cleanest next experiment is to run Raw SODA and Verifier-aware SODA with the same runtime config, same eval50/hard10 files, same GPU count, same decoding parameters and same max retrieval rounds.",
        "",
        "Use the wrapper below to run both strict model-effect arms with identical settings:",
        "",
        "```bash",
        "PYTHON_BIN=/home/zhb/miniconda3/envs/train/bin/python \\",
        "GPUS=0,1 \\",
        "bash scripts/run_soda_verifier_model_ablation.sh",
        "```",
        "",
        "Run strict model-effect arms and evidence-only answer scoring:",
        "",
        "```bash",
        "RUN_TEACHER_SCORE=1 \\",
        "PYTHON_BIN=/home/zhb/miniconda3/envs/train/bin/python \\",
        "GPUS=0,1 \\",
        "bash scripts/run_soda_verifier_model_ablation.sh",
        "```",
        "",
        "Raw SODA command, if running only the baseline arm:",
        "",
        "```bash",
        "RUN_VERIFIER=0 \\",
        "PYTHON_BIN=/home/zhb/miniconda3/envs/train/bin/python \\",
        "GPUS=0,1 \\",
        "bash scripts/run_soda_verifier_model_ablation.sh",
        "```",
        "",
        "After the strict model-effect run completes, rerun `python scripts/analyze_soda_verifier_ablation.py`; the missing strict rows will be filled from the generated `summary.json` or answer jsonl files.",
    ]


def render_report(payload: dict[str, Any]) -> str:
    lines = [
        "# Verifier-Aware SODA Ablation Report",
        "",
        f"- generated_at: `{payload['generated_at']}`",
        "",
        "## Method",
        "",
        "This report uses a paired label-construction ablation. Student rollout, teacher replay, prompt evidence and verifier records are fixed; only the policy that turns candidates into training labels changes:",
        "",
        "- Raw SODA: always uses teacher output as `chosen` and student output as `rejected`.",
        "- Output-only heuristic: accepts teacher output after JSON/action validity and exact quote checks only.",
        "- Verifier-aware SODA: uses the evidence-only verifier verdict to rebuild the chosen action and reject unsafe student/teacher candidates.",
        "",
        "The data-quality side is a verifier-defined label ablation. It directly measures how much label noise the verifier gate removes under its own evidence-only contract; it is not a substitute for an independent human gold audit. To reduce circularity, the report also includes an output-only negative control and exports compact audit cases for human inspection.",
        "",
        "The model-effect side must be interpreted separately. A strict behavioral ablation requires Raw SODA and Verifier-aware SODA LoRA models evaluated under the same runtime config, question files, decoding settings, GPU count and retrieval-round budget.",
        "",
        "## Data Quality Ablation",
        "",
    ]
    for result in payload["quality_experiments"]:
        lines.extend(render_quality_table(result))
        lines.append("")
    lines.extend(render_model_table(payload["model_effects"]))
    lines.extend([""])
    lines.extend(render_paired_model_probe_table(payload["paired_model_probes"]))
    lines.extend([""])
    lines.extend(render_teacher_score_table(payload["teacher_score_effects"]))
    lines.extend([""])
    lines.extend(render_strict_model_effect_status(payload["model_effects"]))
    return "\n".join(lines) + "\n"


def render_audit_cases(payload: dict[str, Any]) -> str:
    lines = [
        "# Verifier-Aware SODA Audit Cases",
        "",
        "These examples are sampled from paired raw teacher/student outputs and verifier records. They are intended for independent manual inspection of the verifier-defined labels.",
        "",
    ]
    labels = {
        "raw_teacher_unsafe": "Raw teacher chosen would be unsafe",
        "student_better_than_teacher": "Student action is safer than teacher candidate",
        "heuristic_false_accept": "Output-only heuristic false accept",
    }
    for result in payload["quality_experiments"]:
        lines.extend([f"## {result['name']}", ""])
        examples = result.get("examples") if isinstance(result.get("examples"), dict) else {}
        for key, title in labels.items():
            cases = examples.get(key) if isinstance(examples.get(key), list) else []
            lines.extend([f"### {title}", ""])
            if not cases:
                lines.extend(["No cases.", ""])
                continue
            for idx, case in enumerate(cases, start=1):
                lines.extend(
                    [
                        f"{idx}. `{case.get('prompt_key')}` {case.get('round') or ''} {case.get('question')}",
                        f"   - correct/student/teacher action: `{case.get('correct_action')}` / `{case.get('student_action')}` / `{case.get('teacher_action')}`",
                        f"   - student_error/teacher_error/teacher_prior: `{case.get('student_error')}` / `{case.get('teacher_error')}` / `{case.get('teacher_prior')}`",
                        f"   - verifier reason: {case.get('label_reason') or ''}",
                        f"   - evidence preview: {case.get('evidence_brief_preview') or ''}",
                        "",
                    ]
                )
    return "\n".join(lines)


def write_audit_artifacts(output_dir: Path, payload: dict[str, Any]) -> None:
    rows = []
    for result in payload["quality_experiments"]:
        examples = result.get("examples") if isinstance(result.get("examples"), dict) else {}
        for case_type, cases in examples.items():
            if not isinstance(cases, list):
                continue
            for case in cases:
                row = {"experiment": result["name"], "case_type": case_type}
                row.update(case)
                rows.append(row)
    with (output_dir / "audit_cases.jsonl").open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    (output_dir / "audit_cases.md").write_text(render_audit_cases(payload), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build verifier-aware SODA data-quality and model-effect ablation report.")
    parser.add_argument("--output-dir", type=Path, default=PROJECT_ROOT / "outputs/soda_verifier_ablation_20260609")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output_dir = args.output_dir if args.output_dir.is_absolute() else PROJECT_ROOT / args.output_dir
    quality = []
    for item in DEFAULT_EXPERIMENTS:
        quality.append(
            analyze_quality_experiment(
                item["name"],
                [project_path(path) for path in item["raw_dirs"]],
                project_path(item["verifier_dir"]),
            )
        )
    payload = {
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
        "quality_experiments": quality,
        "model_effects": collect_model_effects(DEFAULT_MODEL_EVALS),
        "paired_model_probes": collect_paired_model_probes(DEFAULT_PAIRED_MODEL_PROBES),
        "teacher_score_effects": collect_teacher_score_effects(DEFAULT_TEACHER_SCORE_EVALS),
    }
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "summary.json").write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    (output_dir / "report.md").write_text(render_report(payload), encoding="utf-8")
    write_audit_artifacts(output_dir, payload)
    print(output_dir / "report.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
