from __future__ import annotations

import re


ASCII_TOKEN_RE = re.compile(r"[a-z0-9_]+", re.IGNORECASE)
ENTITY_TOKEN_RE = re.compile(r"[\u4e00-\u9fff]{2,8}|[A-Za-z][A-Za-z0-9_.\-]{1,31}")
CAUSAL_QUERY_RE = re.compile(r"为什么|为何|原因|动机|目的|怎么会|为何要|为什么要|为什么会")
REVEAL_QUERY_RE = re.compile(r"阴谋|真相|秘密|识破|揭穿|曝光|暴露|幕后|主使|黑幕|骗局|诡计|怎么回事")
CONCEPT_CRISIS_QUERY_RE = re.compile(r"是什么|本质|来历|为何成为|为什么成为|为什么会成为|危机|祸|患|威胁")
LINE_SPLIT_RE = re.compile(r"[\n\r。！？；]+")
STAGE_NUMBER_RE = re.compile(r"(?:^|[_\-/])(?:level_)?[a-z0-9]+_(\d{2})(?:[_a-z\-/]|$)", re.IGNORECASE)
MAIN_CHAPTER_REF_RE = re.compile(
    r"(?:第\s*([一二三四五六七八九十百零〇两0-9]{1,4})\s*章|([0-9]{1,2})\s*章|level_main[_-]([0-9]{1,2})|main[_-]([0-9]{1,2})|EPISODE\s*([0-9]{1,2}))",
    re.IGNORECASE,
)
MAIN_CHAPTER_SOURCE_RE = re.compile(r"(?:^|[/_])(?:level_)?main[_-](\d{1,2})(?:[-_/]|$)", re.IGNORECASE)
QUERY_CHAR_STOP_CHARS = set("的是了嘛吗呢啊吧呀么什怎为哪件这那其一在和与及或把被让给从向对将会要请问具体指")
LOW_RERANK_QUERY_TYPES = {"fact", "relation"}
HIGH_RERANK_QUERY_TYPES = {"causality", "reasoning", "reveal", "mystery", "answerability"}
QUERY_TYPES = LOW_RERANK_QUERY_TYPES | HIGH_RERANK_QUERY_TYPES
PROFILE_SOURCE_MARKERS = ("handbook_info_table.json", "charword_table.json")
BRANCH_SOURCE_MARKERS = ("/rogue/", "/roguelike/", "/endbook/")
MOEGIRL_SOURCE_MARKERS = ("moegirl.icu", "moegirl/", "萌百世界观资料")
STORY_SOURCE_MARKERS = (
    "activities/",
    "obt/main/",
    "obt/memory/",
    "obt/rogue/",
    "[uc]info/activities/",
)
CONCEPT_DEFINITION_TERMS = {
    "本质",
    "原本",
    "源自",
    "一体",
    "巨兽",
    "神明",
    "代理人",
    "残躯",
    "身躯",
    "沉睡",
    "岁陵",
    "镇压",
}
CONCEPT_CRISIS_TERMS = {
    "苏醒",
    "消灭",
    "身殒",
    "消亡",
    "危害",
    "危机",
    "祸",
    "患",
    "威胁",
    "动乱",
    "开战",
    "进攻",
    "代价",
    "生灵涂炭",
    "尸横遍野",
    "十不存一",
    "灭顶之灾",
}
EXPANSION_STOP_WORDS = {
    "博士",
    "为什么",
    "为何",
    "原因",
    "动机",
    "目的",
    "关闭",
    "开启",
    "进入",
    "离开",
    "全舰",
    "防御系统",
    "系统",
    "因为",
    "所以",
    "就是",
    "然后",
    "这个",
    "那个",
    "他们",
    "我们",
    "你们",
    "自己",
    "已经",
    "还是",
    "没有",
    "不会",
    "一次",
    "本来",
    "开始",
    "完成",
    "行动",
    "战斗",
    "城市",
    "计划",
    "路线",
    "数据",
    "确认",
    "窗口",
    "安全窗口",
}
CHAIN_QUERY_STOP_WORDS = EXPANSION_STOP_WORDS | {
    "什么",
    "怎么",
    "如何",
    "是谁",
    "是怎么",
    "要",
    "会",
    "是",
    "的",
}
ACTION_HINT_TERMS = {
    "关闭",
    "解除",
    "开启",
    "启动",
    "启用",
    "动用",
    "使用",
    "发动",
    "打开",
    "建造",
    "修建",
    "建设",
    "制造",
    "改造",
    "布局",
    "设下",
    "安排",
    "进入",
    "离开",
    "杀死",
    "刺杀",
    "攻击",
    "摧毁",
    "背叛",
    "保护",
    "放弃",
    "加入",
    "成为",
    "形成",
    "控制",
    "识破",
    "揭穿",
    "曝光",
    "暴露",
    "苏醒",
    "消灭",
    "镇压",
    "开战",
    "围猎",
    "狩猎",
}
MOTIVE_HINT_TERMS = {
    "因为",
    "为了",
    "目的",
    "动机",
    "原因",
    "约定",
    "交易",
    "计划",
    "打算",
    "决定",
    "选择",
    "必须",
    "不得不",
    "不必",
    "意味着",
    "会让",
    "让",
    "代价",
    "威胁",
    "危机",
    "祸",
    "患",
    "存亡",
    "一体",
}
OUTCOME_HINT_TERMS = {
    "导致",
    "最终",
    "于是",
    "长驱直入",
    "刺杀",
    "死亡",
    "死",
    "解除",
    "失去",
    "失败",
    "真相",
    "证据",
    "曝光",
    "暴露",
    "识破",
    "揭穿",
    "败露",
    "苏醒",
    "消亡",
    "灭顶之灾",
    "动乱",
    "开战",
    "平息",
    "解决",
    "祸",
    "患",
    "危机",
}
TARGET_CONTEXT_HINT_TERMS = {
    "留守",
    "目标",
    "对象",
    "对付",
    "刺客",
    "暗杀",
}
REVEAL_ANSWER_TERMS = {
    "不能留下证据",
    "留下证据",
    "证据",
    "报告损失",
    "拨给我的钱",
    "钱的窟窿",
    "窟窿",
    "栽赃",
    "嫁祸",
    "被感染者",
    "炸了",
    "炸掉",
    "偷走",
    "内鬼",
    "灭口",
    "绑架",
    "解决掉",
    "同伙",
    "主使",
    "幕后",
    "曝光",
    "败露",
    "全完了",
}
REVEAL_SUPPORT_TERMS = {
    "工厂",
    "设备",
    "物流通道",
    "地下",
    "警备队",
    "议会",
    "拨款",
    "贵族",
    "钱",
    "计划",
}
REVEAL_DIRECT_CONTEXT_TERMS = {
    "澄闪",
    "苏茜",
    "苏茜·格里特",
    "卡拉顿",
    "卡拉顿城",
    "贝希曼",
    "贝希曼伯爵",
    "阴云火花",
}
